---
#firewalld doesn't exist on AWS CentOS 7 by default
- name: Make sure firewalld is installed
  yum: name=firewalld state=present
  when: ansible_os_family == "RedHat"

#The firewalld ruleset configuration will fail
#unless we start firewalld
- name: Enable and start firewalld
  service: name=firewalld state=started enabled=yes
  
- name: Enable the LDAPS firewalld ruleset provided by freeipa
  firewalld: service=freeipa-ldaps permanent=true state=enabled
  notify: reload firewalld
  when: ansible_distribution == "Fedora"


- block:
  - name: Enable HTTPS firewalld services as recommended by FreeIPA
    firewalld:
      service: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ firewall_services }}"

  - name: Enable HTTPS firewalld ports as recommended by FreeIPA
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    with_items: "{{ firewall_ports }}"
  when: ansible_distribution == ("RedHat" or ansible_distribution == "CentOS")


- name: Enable the individual rulesets for CentOS
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - https
    - ldaps
    - kerberos
    - kpasswd
    - dns
    - ntp
  notify: reload firewalld
  when: ansible_distribution != "Fedora" and ansible_os_family == "RedHat"
