---
## Include the specific variables for the OS we are looking to deploy on.
- include_vars: "{{ ansible_os_family }}.yml"

- name: Setup the hostname
  include: configure_hostname.yml

- name: check if the ipa-server package is installed
  shell: '/usr/bin/rpm -qa ipa-server | wc -l'
  register: ipa_installed

## We only install packages if ipa-server isn't installed.
- block:
  - name: Install packages
    include: install_packages.yml


  - name: Install IPA
    include: install_ipa.yml

  - include: firewalld.yml
    when: ipaserver_manage_firewalld
  when:  (ipa_installed.stdout|int == 0 or ipa_force_install)

- debug:
    msg: "{{ ansible_dns.nameservers[0] }}"

